spring: 
  application: 
    name: api-gateway
server: 
  port: 3333
zuul:                                      #routes to url
  routes: 
    compute: 
      path: /compute/**
      serviceId: COMPUTE-SERVICE
    api-a-url:  #routes to url
      path: /api-a-url/**
      url: http://localhost:2222/
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/