spring:
		application:
		name: api-gateway
server:
		port: 3333

# routes to serviceId
zuul:
	    routes:
	    compute: 
	    path: /compute/**
		serviceId: COMPUTE-SERVICE
# routes to url
zuul: 
routes: 
api-a-url:
path: /api-a-url/**
zuul:
routes:
api-a-url:
url: http://localhost:2222/

eureka: 
client: 
serviceUrl:
defaultZone: http://localhost:1111/eureka/